Use train upper constraints
Travis builds were failing due to the use of f-strings:

  File "/home/travis/build/stackhpc/networking-generic-switch/.tox/py27/lib/python2.7/site-packages/netmiko/cisco_base_connection.py", line 143
    msg = f"Login failed: {self.host}"
                                     ^
SyntaxError: invalid syntax

Change-Id: Ie1cc8e8470a86f4692a0530443d362c5cd139c7a